from django.urls import path

from apps.applydesk.views.application import (
    application_create,
    application_delete,
    application_detail,
    application_edit,
    application_form,
    application_list,
    change_status,
    move_application,
)
from apps.applydesk.views.application_document import (
    attach_document,
    attach_document_modal,
    detach_document,
    upload_document_for_application,
)
from apps.applydesk.views.company import (
    company_create,
    company_delete,
    company_detail,
    company_edit,
    company_list,
)
from apps.applydesk.views.dashboard import dashboard
from apps.applydesk.views.document import (
    document_detail,
    document_inspector,
    document_list,
    document_upload_button,
    document_upload_form,
    generate_document_view,
    open_document_modal,
    upload_document,
)
from apps.applydesk.views.document_schema import (
    schema_create,
    schema_duplicate,
    schema_editor,
    schema_editor_new,
    schema_field_delete,
    schema_field_edit,
    schema_field_form,
    schema_field_move,
    schema_field_store,
    schema_field_update,
    schema_list,
    schema_publish,
    schema_update,
)
from apps.applydesk.views.pipeline import application_pipeline

urlpatterns = [
    path("", dashboard, name="dashboard"),
    path(
        "applications/",
        application_list,
        name="application_list",
    ),
    path(
        "applications/create/",
        application_create,
        name="application_create",
    ),
    path(
        "applications/<int:application_id>/edit/",
        application_edit,
        name="application_edit",
    ),
    path(
        "applications/form/",
        application_form,
        name="application_form",
    ),
    path(
        "applications/<int:application_id>/",
        application_detail,
        name="application_detail",
    ),
    path(
        "applications/<int:application_id>/delete/",
        application_delete,
        name="application_delete",
    ),
    path(
        "applications/<int:application_id>/change-status/",
        change_status,
        name="change_status",
    ),
    path(
        "applications/move/",
        move_application,
        name="move_application",
    ),
    path(
        "applications/pipeline/",
        application_pipeline,
        name="application_pipeline",
    ),
    path(
        "applications/<int:application_id>/documents/upload/",
        upload_document_for_application,
        name="upload_document_for_application",
    ),
    path(
        "companies/",
        company_list,
        name="company_list",
    ),
    path(
        "companies/<int:company_id>/",
        company_detail,
        name="company_detail",
    ),
    path("companies/create/", company_create, name="company_create"),
    path("companies/<int:company_id>/edit/", company_edit, name="company_edit"),
    path("companies/<int:company_id>/delete/", company_delete, name="company_delete"),
    path(
        "documents/",
        document_list,
        name="document_list",
    ),
    path(
        "documents/upload-form/",
        document_upload_form,
        name="document_upload_form",
    ),
    path(
        "documents/upload-button/",
        document_upload_button,
        name="document_upload_button",
    ),
    path(
        "documents/upload/",
        upload_document,
        name="upload_document",
    ),
    path(
        "applications/<int:application_id>/documents/modal/",
        attach_document_modal,
        name="attach_document_modal",
    ),
    path(
        "applications/<int:application_id>/documents/<int:document_id>/attach/",
        attach_document,
        name="attach_document",
    ),
    path(
        "applications/documents/<int:link_id>/detach/",
        detach_document,
        name="detach_document",
    ),
    path(
        "documents/<int:pk>/",
        document_detail,
        name="document_detail",
    ),
    path(
        "documents/<int:pk>/inspector/",
        document_inspector,
        name="document_inspector",
    ),
    path(
        "applications/<int:application_id>/documents/<str:document_type>/modal/",
        open_document_modal,
        name="document_modal",
    ),
    path(
        "applications/<int:application_id>/documents/<str:document_type>/generate/",
        generate_document_view,
        name="generate_document",
    ),
    path("documents/schemas/editor/new/", schema_editor_new, name="schema_editor_new"),
    path(
        "documents/schemas/editor/<int:schema_id>/",
        schema_editor,
        name="schema_editor",
    ),
    path(
        "documents/schemas/<int:schema_id>/fields/new/",
        schema_field_form,
        name="schema_field_form",
    ),
    path(
        "documents/schemas/<int:schema_id>/fields/",
        schema_field_store,
        name="schema_field_store",
    ),
    path("documents/schemas/save/", schema_create, name="schema_create"),
    path("documents/schemas/save/<int:schema_id>/", schema_update, name="schema_save"),
    path(
        "documents/schemas/<int:schema_id>/duplicate/",
        schema_duplicate,
        name="schema_duplicate",
    ),
    path(
        "documents/schemas/list/",
        schema_list,
        name="schema_list",
    ),
    path(
        "documents/schemas/<int:schema_id>/publish/",
        schema_publish,
        name="schema_publish",
    ),
    path(
        "documents/schemas/<int:schema_id>/fields/<str:field_id>/edit/",
        schema_field_edit,
        name="schema_field_edit",
    ),
    path(
        "documents/schemas/<int:schema_id>/fields/<str:field_id>/update/",
        schema_field_update,
        name="schema_field_update",
    ),
    path(
        "documents/schemas/<int:schema_id>/fields/<str:field_id>/delete/",
        schema_field_delete,
        name="schema_field_delete",
    ),
    path(
        "schemas/<int:schema_id>/fields/<str:field_id>/move/",
        schema_field_move,
        name="schema_field_move",
    ),
]
