# Generated by Django 6.0.6 on 2026-07-05 16:50

import apps.applydesk.services.documents.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_title', models.CharField(max_length=100)),
                ('position_description', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('location_type', models.CharField(blank=True, choices=[('remote', 'Remote'), ('onsite', 'On-site'), ('hybrid', 'Hybrid')], max_length=20, null=True)),
                ('status', models.CharField(choices=[('saved', 'Saved'), ('pre_call', 'Pre-screening call'), ('prepared', 'Prepared'), ('applied', 'Applied'), ('waiting', 'Waiting'), ('interview', 'Interview'), ('offer', 'Offer'), ('rejected', 'Rejected'), ('closed', 'Closed'), ('archived', 'Archived')], default='saved', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('priority', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('I', 'Initiative')], default='B', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status_changed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('street', models.CharField(blank=True, max_length=200, null=True)),
                ('street_number', models.CharField(blank=True, max_length=10, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('career_site', models.URLField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='B', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('cv', 'CV'), ('cover_letter', 'Cover Letter'), ('certificate_work', 'Work Certificate'), ('certificate_school', 'School Certificate'), ('certificate', 'Certificate'), ('photo', 'Photo'), ('other', 'Other')], max_length=50)),
                ('file', models.FileField(upload_to=apps.applydesk.services.documents.storage.document_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('cv', 'CV'), ('cover_letter', 'Cover Letter'), ('certificate_work', 'Work Certificate'), ('certificate_school', 'School Certificate'), ('certificate', 'Certificate'), ('photo', 'Photo'), ('other', 'Other')], max_length=50)),
                ('schema', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationRequiredDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=50)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_documents', to='applydesk.application')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=30, null=True)),
                ('to_status', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='applydesk.application')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='applydesk.company'),
        ),
        migrations.CreateModel(
            name='DocumentDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=50)),
                ('field_values', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='applydesk.application')),
                ('source_draft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='applydesk.documentdraft')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary_cv', models.BooleanField(default=False)),
                ('is_primary_cover_letter', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_documents', to='applydesk.application')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_applications', to='applydesk.document')),
            ],
            options={
                'unique_together': {('application', 'document')},
            },
        ),
        migrations.CreateModel(
            name='DocumentSchemaVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('data', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='applydesk.documentschema')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'draft')), fields=('schema',), name='unique_draft_per_schema')],
            },
        ),
    ]
