# Generated by Django 6.0.6 on 2026-07-05 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applydesk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentschemaversion',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
    ]
