# Generated by Django 6.0.5 on 2026-05-27 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applydesk', '0002_application_created_at_application_notes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='position_name',
            new_name='position_title',
        ),
    ]
