# Generated by Django 6.0.5 on 2026-05-27 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applydesk', '0003_rename_position_name_application_position_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('saved', 'Saved'), ('prepared', 'Prepared'), ('applied', 'Applied'), ('waiting', 'Waiting'), ('interview', 'Interview'), ('offer', 'Offer'), ('rejected', 'Rejected'), ('archived', 'Archived')], max_length=20),
        ),
    ]
