# Generated by Django 6.0.6 on 2026-07-05 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applydesk', '0003_alter_documentschemaversion_version'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='documentschemaversion',
            name='unique_draft_per_schema',
        ),
    ]
