# Generated by Django 6.0.6 on 2026-07-05 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applydesk', '0004_remove_documentschemaversion_unique_draft_per_schema'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='documentschemaversion',
            index=models.Index(fields=['schema', 'status'], name='applydesk_d_schema__e23ff5_idx'),
        ),
    ]
