# Generated by Django 6.0.6 on 2026-07-05 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applydesk', '0005_documentschemaversion_applydesk_d_schema__e23ff5_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentschemaversion',
            name='version',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
