# Generated by Django 6.0.5 on 2026-06-05 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applydesk', '0005_application_contact_email_application_contact_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='applydesk.company'),
        ),
        migrations.AlterField(
            model_name='company',
            name='street_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='zipcode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
