# Generated by Django 6.0.6 on 2026-07-05 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applydesk', '0006_alter_documentschemaversion_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentschemaversion',
            name='version',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
