# Generated by Django 6.0.6 on 2026-07-22 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applydesk', '0007_alter_documentschemaversion_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentschemaversion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
